# Tutorial: NumPy

In [ ]:
__author__ = "Christopher Potts, Will Monroe, and Lucy Li"
__version__ = "CS224u, Stanford, Spring 2020"

## Contents

1. [Motivation](#Motivation)
1. [Vectors](#Vectors)
  1. [Vector Initialization](#Vector-Initialization)
  1. [Vector indexing](#Vector-indexing)
  1. [Vector assignment](#Vector-assignment)
  1. [Vectorized operations](#Vectorized-operations)
  1. [Comparison with Python lists](#Comparison-with-Python-lists)
1. [Matrices](#Matrices)
  1. [Matrix initialization](#Matrix-initialization)
  1. [Matrix indexing](#Matrix-indexing)
  1. [Matrix assignment](#Matrix-assignment)
  1. [Matrix reshaping](#Matrix-reshaping)
  1. [Numeric operations](#Numeric-operations)
1. [Practical example: a shallow neural network](#Practical-example:-a-shallow-neural-network)
1. [Going beyond NumPy alone](#Going-beyond-NumPy-alone)
  1. [Pandas](#Pandas)
  1. [Scikit-learn](#Scikit-learn)
  1. [SciPy](#SciPy)
  1. [Matplotlib](#Matplotlib)

## Motivation

Why should we care about NumPy? 

- It allows you to perform tons of operations on vectors and matrices. 
- It makes things run faster than naive for-loop implementations (a.k.a. vectorization). 
- We use it in our class (see files prefixed with `np_` in your `cs224u` directory). 
- It's used a ton in machine learning / AI. 
- Its arrays are often inputs into other important Python packages' functions. 

In Jupyter notebooks, NumPy documentation is two clicks away: Help -> NumPy reference. 

## Vectors

In [2]:
import numpy as np

### Vector Initialization

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
# convert list to numpy array
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
# convert numpy array to list
np.ones(5).tolist()

[1.0, 1.0, 1.0, 1.0, 1.0]

In [7]:
# one float => all floats
np.array([1.0,2,3,4,5])

array([1., 2., 3., 4., 5.])

In [8]:
# same as above
np.array([1,2,3,4,5], dtype='float')

array([1., 2., 3., 4., 5.])

In [9]:
# spaced values in interval
np.array([x for x in range(20) if x % 2 == 0])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# same as above
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# random floats in [0, 1)
np.random.random(10)

array([0.82260552, 0.71205449, 0.47775054, 0.0184577 , 0.89053877,
       0.25864656, 0.59003324, 0.47460967, 0.18927918, 0.8536697 ])

In [12]:
# random integers
np.random.randint(5, 15, size=10)

array([13,  8, 12, 12,  9, 13, 11, 10, 14, 10])

### Vector indexing

In [13]:
x = np.array([10,20,30,40,50])

In [14]:
x[0]

10

In [15]:
# slice
x[0:2]

array([10, 20])

In [16]:
x[0:1000]

array([10, 20, 30, 40, 50])

In [17]:
# last value
x[-1]

50

In [18]:
# last value as array
x[[-1]]

array([50])

In [19]:
# last 3 values
x[-3:]

array([30, 40, 50])

In [20]:
# pick indices
x[[0,2,4]]

array([10, 30, 50])

### Vector assignment

Be careful when assigning arrays to new variables! 

In [21]:
x2 = x # try this line instead
#x2 = x.copy()

In [23]:
x2[0] = 10
x2

array([10, 20, 30, 40, 50])

In [24]:
x2[[1,2]] = 10

x2

array([10, 10, 10, 40, 50])

In [25]:
x2[[3,4]] = [0, 1]

x2

array([10, 10, 10,  0,  1])

In [26]:
# check if the original vector changed
x

array([10, 10, 10,  0,  1])

### Vectorized operations

In [27]:
x.sum()

31

In [28]:
x.mean()

6.2

In [29]:
x.max()

10

In [30]:
x.argmax()

0

In [31]:
np.log(x)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([2.30258509, 2.30258509, 2.30258509,       -inf, 0.        ])

In [32]:
np.exp(x)

array([2.20264658e+04, 2.20264658e+04, 2.20264658e+04, 1.00000000e+00,
       2.71828183e+00])

In [33]:
x + x  # Try also with *, -, /, etc.

array([20, 20, 20,  0,  2])

In [34]:
x + 1

array([11, 11, 11,  1,  2])

### Comparison with Python lists

Vectorizing your mathematical expressions can lead to __huge__ performance gains. The following example is meant to give you a sense for this. It compares applying `np.log` to each element of a list with 10 million values with the same operation done on a vector.

In [35]:
# log every value as list, one by one
def listlog(vals):
    return [np.log(y) for y in vals]

In [36]:
# get random vector
samp = np.random.random_sample(int(1e7))+1
samp

array([1.02558402, 1.51080572, 1.61121807, ..., 1.021054  , 1.57850962,
       1.986819  ])

In [37]:
%time _ = np.log(samp)

CPU times: user 105 ms, sys: 23.6 ms, total: 128 ms
Wall time: 126 ms


In [38]:
%time _ = listlog(samp)

CPU times: user 13.8 s, sys: 195 ms, total: 14 s
Wall time: 14 s


## Matrices

The matrix is the core object of machine learning implementations. 

### Matrix initialization

In [39]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
np.array([[1,2,3], [4,5,6]], dtype='float')

array([[1., 2., 3.],
       [4., 5., 6.]])

In [41]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### Matrix indexing

In [45]:
X = np.array([[1,2,3], [4,5,6]])
X

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
X[0]

array([1, 2, 3])

In [47]:
X[0,0]

1

In [48]:
# get row
X[0, : ]

array([1, 2, 3])

In [49]:
# get column
X[ : , 0]

array([1, 4])

In [50]:
# get multiple columns
X[ : , [0,2]]

array([[1, 3],
       [4, 6]])

### Matrix assignment

In [51]:
X2 = X # try this line instead
# X2 = X.copy()

X2

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
X2[0,0] = 20

X2

array([[20,  2,  3],
       [ 4,  5,  6]])

In [53]:
X2[0] = 3

X2

array([[3, 3, 3],
       [4, 5, 6]])

In [54]:
X2[: , -1] = [5, 6]

X2

array([[3, 3, 5],
       [4, 5, 6]])

In [55]:
# check if original matrix changed
X

array([[3, 3, 5],
       [4, 5, 6]])

### Matrix reshaping

In [56]:
z = np.arange(1, 7)

z

array([1, 2, 3, 4, 5, 6])

In [57]:
z.shape

(6,)

In [58]:
Z = z.reshape(2,3)

Z

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
Z.shape

(2, 3)

In [60]:
Z.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [61]:
# same as above
Z.flatten()

array([1, 2, 3, 4, 5, 6])

In [62]:
# transpose
Z.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### Numeric operations

In [63]:
A = np.array(range(1,7), dtype='float').reshape(2,3)

A

array([[1., 2., 3.],
       [4., 5., 6.]])

In [64]:
B = np.array([1, 2, 3])

In [65]:
# not the same as A.dot(B)
A * B

array([[ 1.,  4.,  9.],
       [ 4., 10., 18.]])

In [66]:
A + B

array([[2., 4., 6.],
       [5., 7., 9.]])

In [67]:
A / B

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [68]:
# matrix multiplication
A.dot(B)

array([14., 32.])

In [69]:
B.dot(A.T)

array([14., 32.])

In [70]:
A.dot(A.T)

array([[14., 32.],
       [32., 77.]])

In [71]:
# outer product
# multiplying each element of first vector by each element of the second
np.outer(B, B)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

## Practical example: a shallow neural network

The following is a practical example of numerical operations on NumPy matrices. 

In our class, we have a shallow neural network implemented in `np_shallow_neural_network.py`. See how the forward and backward passes use no for loops, and instead takes advantage of NumPy's ability to vectorize manipulations of data. 

```python
def forward_propagation(self, x):
    h = self.hidden_activation(x.dot(self.W_xh) + self.b_xh)
    y = softmax(h.dot(self.W_hy) + self.b_hy)
    return h, y

def backward_propagation(self, h, predictions, x, labels):
    y_err = predictions.copy()
    y_err[np.argmax(labels)] -= 1
    d_b_hy = y_err
    h_err = y_err.dot(self.W_hy.T) * self.d_hidden_activation(h)
    d_W_hy = np.outer(h, y_err)
    d_W_xh = np.outer(x, h_err)
    d_b_xh = h_err
    return d_W_hy, d_b_hy, d_W_xh, d_b_xh
```

The forward pass essentially computes the following: 
    $$h = f(xW_{xh} + b_{xh})$$
    $$y = \text{softmax}(hW_{hy} + b_{hy}),$$
where $f$ is `self.hidden_activation`. 

The backward pass propagates error by computing local gradients and chaining them. Feel free to learn more about backprop [here](http://cs231n.github.io/optimization-2/), though it is not necessary for our class. Also look at this [neural networks case study](http://cs231n.github.io/neural-networks-case-study/) to see another example of how NumPy can be used to implement forward and backward passes of a simple neural network. 

## Going beyond NumPy alone

These are examples of how NumPy can be used with other Python packages. 

### Pandas
We can convert numpy matrices to Pandas dataframes. In the following example, this is useful because it allows us to label each row. You may have noticed this being done in our first unit on distributed representations. 

In [72]:
import pandas as pd

In [73]:
count_df = pd.DataFrame(
    np.array([
        [1,0,1,0,0,0],
        [0,1,0,1,0,0],
        [1,1,1,1,0,0],
        [0,0,0,0,1,1],
        [0,0,0,0,0,1]], dtype='float64'),
    index=['gnarly', 'wicked', 'awesome', 'lame', 'terrible'])
count_df

0    1    2    3    4    5
gnarly    1.0  0.0  1.0  0.0  0.0  0.0
wicked    0.0  1.0  0.0  1.0  0.0  0.0
awesome   1.0  1.0  1.0  1.0  0.0  0.0
lame      0.0  0.0  0.0  0.0  1.0  1.0
terrible  0.0  0.0  0.0  0.0  0.0  1.0

### Scikit-learn

In `sklearn`, NumPy matrices are the most common input and output and thus a key to how the library's numerous methods can work together. Many of the cs224u's model built by Chris operate just like `sklearn` ones, such as the classifiers we used for our sentiment analysis unit. 

In [74]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn import datasets

In [77]:
iris = datasets.load_iris()
X = iris.data
y = iris.target
print(type(X))
print(X)
print("Dimensions of X:", X.shape)
print(type(y))
print("Dimensions of y:", y.shape)

<class 'numpy.ndarray'>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3

In [76]:
# split data into train/test
X_iris_train, X_iris_test, y_iris_train, y_iris_test = train_test_split(
    X, y, train_size=0.7, test_size=0.3)
print("X_iris_train:", type(X_iris_train))
print("y_iris_train:", type(y_iris_train))
print()

# start up model
maxent = LogisticRegression(
    fit_intercept=True, 
    solver='liblinear', 
    multi_class='auto')

# train on train set
maxent.fit(X_iris_train, y_iris_train)

# predict on test set
iris_predictions = maxent.predict(X_iris_test)
fnames_iris = iris['feature_names']
tnames_iris = iris['target_names']

# how well did our model do?
print(classification_report(y_iris_test, iris_predictions, target_names=tnames_iris))

X_iris_train: <class 'numpy.ndarray'>
y_iris_train: <class 'numpy.ndarray'>

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        12
  versicolor       1.00      0.88      0.93        16
   virginica       0.89      1.00      0.94        17

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45



### SciPy

SciPy contains what may seem like an endless treasure trove of operations for linear algebra, optimization, and more.  It is built so that everything can work with NumPy arrays. 

In [78]:
from scipy.spatial.distance import cosine
from scipy.stats import pearsonr
from scipy import linalg

In [79]:
# cosine distance
a = np.random.random(10)
b = np.random.random(10)
cosine(a, b)

0.1801836228532132

In [80]:
# pearson correlation (coeff, p-value)
pearsonr(a, b)

(0.10876876947593911, 0.7648632772381749)

In [81]:
# inverse of matrix
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
linalg.inv(A)

array([[-1.48,  0.36,  0.88],
       [ 0.56,  0.08, -0.36],
       [ 0.16, -0.12,  0.04]])

To learn more about how NumPy can be combined with SciPy and Scikit-learn for machine learning, check out this [notebook tutorial](https://github.com/cgpotts/csli-summer/blob/master/advanced_python/intro_to_python_ml.ipynb) by Chris Potts and Will Monroe. (You may notice that over half of this current notebook is modified from theirs.) Their tutorial also has some interesting exercises in it! 

### Matplotlib

In [82]:
import matplotlib.pyplot as plt

In [ ]:
a = np.sort(np.random.random(30))
b = a**2
c = np.log(a)
plt.plot(a, b, label='y = x^2')
plt.plot(a, c, label='y = log(x)')
plt.legend()
plt.title("Some functions")
plt.show()